use strum_macros::{Display, EnumIter, EnumString};

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, EnumString, Display, EnumIter,
)]
#[strum(serialize_all = "kebab-case")]
pub enum Word {
    // Particles
    Li,
    E,
    La,
    Pi,
    O,
    En,
    Anu,
    Ala,
    Kin, // Often considered a particle in some contexts (pu: emphasis)

    // Pronouns (can also be regular words)
    Mi,
    Sina,
    Ona,
    Ni,

    // Prepositions
    Lon,
    // Tawa - in Nimi Pu
    Tan,
    // Kepeken - in Nimi Pu
    Poka,
    Sama,

    // Nimi Pu (The core 120)
    A,
    Akesi,
    Alasa,
    Ale,
    Ali,
    Anpa,
    Ante,
    Awen,
    Esun,
    Ijo,
    Ike,
    Ilo,
    Insa,
    Jaki,
    Jan,
    Jelo,
    Jo,
    Kala,
    Kalama,
    Kama,
    Kasi,
    Ken,
    Kepeken,
    Kili,
    Kiwen,
    Ko,
    Kon,
    Kule,
    Kulupu,
    Kute,
    Lape,
    Laso,
    Lawa,
    Len,
    Lete,
    Lili,
    Linja,
    Lipu,
    Loje,
    Luka,
    Lukin,
    Lupa,
    Ma,
    Mama,
    Mani,
    Meliji,
    Mije,
    Moku,
    Moli,
    Monsi,
    Mu,
    Mun,
    Musi,
    Mute,
    Namako,
    Nanpa,
    Nasa,
    Nasin,
    Nena,
    Nimi,
    Noka,
    Oko,
    Olin,
    Open,
    Pakala,
    Pali,
    Palisa,
    Pan,
    Pana,
    Pilin,
    Pimeja,
    Pini,
    Pipi,
    Pona,
    Pu,
    Seli,
    Selo,
    Seme,
    Sepi,
    Sewi,
    Sijelo,
    Sike,
    Sin,
    Sinpin,
    Sitelen,
    Sona,
    Soweli,
    Suli,
    Suno,
    Supa,
    Suwi,
    Taso,
    Tawa,
    Telo,
    Tenpo,
    Toki,
    Tomo,
    Tu,
    Unpa,
    Uta,
    Utala,
    Walo,
    Wan,
    Waso,
    Wawa,
    Weka,
    Wile,

    // Nimi Ku (Common selection)
    Epiku,
    Jasima,
    Kijetesantakalu,
    Kokosila,
    Ku,
    Lanpan,
    Leqo,
    Miso,
    Monsuta,
    N,
    Pake,
    Soko,
    Tonso,
    // Proper names are usually handled separately by the lexer,
    // but we can have a variant for unrecognized words if needed,
    // though 'strum' is for fixed variants.
    // We will handle proper nouns in the Token enum in the parser usually,
    // but strictly speaking, `Word` here represents the content words.
}

impl Word {
    pub fn is_particle(&self) -> bool {
        matches!(
            self,
            Word::Li | Word::E | Word::La | Word::Pi | Word::O | Word::En | Word::Anu
        )
    }

    pub fn is_preposition(&self) -> bool {
        matches!(
            self,
            Word::Lon | Word::Kepeken | Word::Tawa | Word::Tan | Word::Poka | Word::Sama
        )
    }

    pub fn part_of_speech(&self) -> &'static str {
        match self {
            Word::Li | Word::E | Word::La | Word::Pi | Word::O | Word::En | Word::Anu => "particle",
            Word::Mi | Word::Sina | Word::Ona | Word::Ni => "pronoun", // Can also be modifier/head
            Word::Lon | Word::Tan | Word::Poka | Word::Sama | Word::Kepeken | Word::Tawa => {
                "preposition"
            }
            _ => "content word",
        }
    }

    pub fn definition(&self) -> &'static str {
        match self {
            // Particles
            Word::Li => "separates subject and verb",
            Word::E => "introduces direct object",
            Word::La => "context separator (if/when)",
            Word::Pi => "of (regroups modifiers)",
            Word::O => "vocative or imperative marker",
            Word::En => "and (combines subjects)",
            Word::Anu => "or",
            Word::Ala => "not, nothing, no",
            Word::Kin => "also, too, indeed",

            // Pronouns
            Word::Mi => "I, me, my",
            Word::Sina => "you, your",
            Word::Ona => "he, she, it, they",
            Word::Ni => "this, that",

            // Prepositions
            Word::Lon => "in, at, on, true, to be",
            Word::Tan => "from, by, because of",
            Word::Poka => "side, hip, nearby, with",
            Word::Sama => "same, similar, like",

            // Core words (Pu)
            Word::A => "emphatic particle (emotion)",
            Word::Akesi => "reptile, amphibian",
            Word::Alasa => "hunt, gather, try",
            Word::Ale => "all, everything, universe",
            Word::Ali => "all, everything (variant of ale)",
            Word::Anpa => "down, bottom, lower",
            Word::Ante => "different, other, change",
            Word::Awen => "stay, wait, keep",
            Word::Esun => "market, shop, trade",
            Word::Ijo => "thing, object, matter",
            Word::Ike => "bad, evil, negative",
            Word::Ilo => "tool, device, machine",
            Word::Insa => "inside, center, stomach",
            Word::Jaki => "dirty, gross, trash",
            Word::Jan => "person, people, human",
            Word::Jelo => "yellow",
            Word::Jo => "have, carry, contain",
            Word::Kala => "fish, sea creature",
            Word::Kalama => "sound, noise, voice",
            Word::Kama => "come, become, happen",
            Word::Kasi => "plant, vegetation, leaf",
            Word::Ken => "can, ability, possibility",
            Word::Kepeken => "use, with, using",
            Word::Kili => "fruit, vegetable",
            Word::Kiwen => "hard object, metal, stone",
            Word::Ko => "semi-solid, powder, gum",
            Word::Kon => "air, wind, spirit",
            Word::Kule => "color, paint",
            Word::Kulupu => "group, community, society",
            Word::Kute => "ear, hear, listen",
            Word::Lape => "sleep, rest",
            Word::Laso => "blue, green",
            Word::Lawa => "head, mind, lead, control",
            Word::Len => "cloth, clothing, cover",
            Word::Lete => "cold, cool, raw",
            Word::Lili => "small, little, young",
            Word::Linja => "long flexible object, cord, hair",
            Word::Lipu => "flat object, book, paper",
            Word::Loje => "red",
            Word::Luka => "hand, arm, five",
            Word::Lukin => "eye, see, look, visual",
            Word::Lupa => "hole, door, window",
            Word::Ma => "earth, land, country",
            Word::Mama => "parent, ancestor, creator",
            Word::Mani => "money, cash, wealth",
            Word::Meliji => "female, woman, wife (archaic)",
            Word::Mije => "male, man, husband",
            Word::Moku => "eat, drink, food",
            Word::Moli => "die, dead, kill",
            Word::Monsi => "back, behind, rear",
            Word::Mu => "animal noise",
            Word::Mun => "moon, night sky object",
            Word::Musi => "fun, playing, game, art",
            Word::Mute => "many, a lot, much",
            Word::Namako => "spice, extra, adornment",
            Word::Nanpa => "number, -th (ordinal)",
            Word::Nasa => "strange, silly, drunk",
            Word::Nasin => "way, custom, path, road",
            Word::Nena => "bump, button, hill, nose",
            Word::Nimi => "name, word",
            Word::Noka => "leg, foot",
            Word::Oko => "eye (variant of lukin)",
            Word::Olin => "love",
            Word::Open => "open, begin, start",
            Word::Pakala => "accident, mistake, break",
            Word::Pali => "do, work, make",
            Word::Palisa => "long hard object, stick",
            Word::Pan => "cereal, grain, bread",
            Word::Pana => "give, send, emit",
            Word::Pilin => "heart, feeling, touch, sense",
            Word::Pimeja => "black, dark",
            Word::Pini => "end, tip, finish",
            Word::Pipi => "bug, insect",
            Word::Pona => "good, simple, positive",
            Word::Pu => "interact with the official Toki Pona book",
            Word::Seli => "fire, warmth, heat",
            Word::Selo => "outside, surface, skin, shell",
            Word::Seme => "what? which? (question word)",
            Word::Sepi => "sexual features (archaic)",
            Word::Sewi => "high, up, above, top, divine",
            Word::Sijelo => "body, physical state",
            Word::Sike => "round, circle, ball, wheel",
            Word::Sin => "new, fresh, another",
            Word::Sinpin => "face, foremost, front, wall",
            Word::Sitelen => "image, picture, writing",
            Word::Sona => "know, understand, wisdom",
            Word::Soweli => "animal, beast, land mammal",
            Word::Suli => "big, heavy, large, important",
            Word::Suno => "sun, light, brightness",
            Word::Supa => "horizontal surface, furniture",
            Word::Suwi => "sweet, fragrance, cute",
            Word::Taso => "only, sole, but",
            Word::Tawa => "move, go, to, for",
            Word::Telo => "water, liquid, fluid",
            Word::Tenpo => "time, duration, moment",
            Word::Toki => "language, talk, speech, communicate",
            Word::Tomo => "indoor space, building, house",
            Word::Tu => "two, divide",
            Word::Unpa => "sex, sexual",
            Word::Uta => "mouth, lips, oral",
            Word::Utala => "fight, battle, challenge",
            Word::Walo => "white, pale",
            Word::Wan => "one, unique, unite",
            Word::Waso => "bird, flying creature",
            Word::Wawa => "strong, power, energy",
            Word::Weka => "away, absent, missing",
            Word::Wile => "want, need, desire, must",

            // Ku / Other
            Word::Epiku => "epic, awesome",
            Word::Jasima => "mirror, reflect",
            Word::Kijetesantakalu => "raccoon-like animal",
            Word::Kokosila => "speak not-toki-pona while others speak toki pona",
            Word::Ku => "interact with the Toki Pona Dictionary",
            Word::Lanpan => "seize, steal, capture",
            Word::Leqo => "block, square, brick",
            Word::Miso => "misunderstand? (rare)",
            Word::Monsuta => "fear, monster, scary",
            Word::N => "hmm, n",
            Word::Pake => "block, stop (archaic?)",
            Word::Soko => "fungus, mushroom",
            Word::Tonso => "non-binary, trans",
        }
    }
}
